version: "3"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
    driver: local
